import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fixture,begin,prompt,pre,task,specialist,installTask,agent,finish,ev,put,state} from './helpers.mjs';
import {validateTask,route,TASK,digest,sourceDigest,withState} from '../runtime/core.mjs';
import {handleEvent} from '../runtime/events.mjs';

test('A01: production writes without route are blocked',t=>{const r=fixture(t);begin(r);assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'changed'}),/route/);});
test('A02: runtime/config writes are protected',t=>{const r=fixture(t);begin(r);for(const p of ['.claude/settings.json','.claude/aae/runtime/hook.mjs','.claude/aae/state/local.json','CLAUDE.md','.gitignore'])assert.throws(()=>pre(r,'Write',{file_path:path.join(r,p),content:'bad'}));});
test('A03: unfilled shipped template cannot activate',t=>{const r=fixture(t);begin(r);const c=JSON.parse(fs.readFileSync(path.join(r,'.claude/aae/templates/TASK.template.json')));put(r,TASK,c);assert.throws(()=>route(r));});
test('A04: two-line/formless route cannot activate',t=>{const r=fixture(t);begin(r);put(r,TASK,{mode:'lean',design_freeze:false});assert.throws(()=>route(r),/ontbrekend/);});
test('A05: analysis is not implementation permission',t=>{const r=fixture(t);begin(r);installTask(r,task({phase:'analysis'}));assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'bad'}),/Analyse/);assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'docs/aae/notes/analysis.md'),content:'Evidence'}));});
test('schema rejects unknown fields and unsafe path forms',()=>{for(const patch of [{foo:1},{mode:'Lean / Standard / High Assurance'},{approval_required:'false'},{scope:{read:[],write:['../outside']}}])assert.throws(()=>validateTask(task(patch)));});
test('schema requires high-risk checks and an independent reviewer',()=>{const c=task({risk:'high',mode:'high-assurance',risk_flags:['authorization']});assert.throws(()=>validateTask(c),/kwaliteitsondergrens/);for(const kind of ['authorization-positive','authorization-negative','tenant-isolation'])c.test_plan.push({kind,method:'command',description:'Concrete test'});assert.throws(()=>validateTask(c),/onafhankelijke/);});
test('task edits must be whole-file validated JSON writes',t=>{const r=fixture(t);begin(r);assert.throws(()=>pre(r,'Edit',{file_path:path.join(r,TASK),old_string:'analysis',new_string:'implementation'}),/volledig JSON/);assert.throws(()=>pre(r,'Write',{file_path:path.join(r,TASK),content:'{}'}));});
test('valid small scope works but adjacent names do not match',t=>{const r=fixture(t);begin(r);installTask(r,task());assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'new'}));assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js-evil'),content:'new'}),/schrijfscope/);});
test('A20: symlinked notes cannot redirect into code',t=>{const r=fixture(t);begin(r);fs.mkdirSync(path.join(r,'docs/aae/notes'),{recursive:true});fs.symlinkSync(path.join(r,'src/a.js'),path.join(r,'docs/aae/notes/a.md'));assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'docs/aae/notes/a.md'),content:'evil'}),/Symbolische/);});
test('symlinked scope parent is rejected',t=>{const r=fixture(t);begin(r);fs.symlinkSync(path.join(r,'src'),path.join(r,'linked'),'dir');installTask(r,task({scope:{read:[],write:['linked/a.js']}}));assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'linked/a.js'),content:'evil'}),/Symbolische/);});
test('secrets are not direct read/write targets',t=>{const r=fixture(t);begin(r);assert.throws(()=>pre(r,'Read',{file_path:path.join(r,'.env')}),/secrets/);assert.throws(()=>installTask(r,task({scope:{read:[],write:['.env']}})),/Systeembestanden/);});
test('A06/A07: unplanned Agent and Task calls rejected',t=>{const r=fixture(t);begin(r);installTask(r,task());for(const tool of ['Agent','Task'])assert.throws(()=>pre(r,tool,{subagent_type:'aae-security-reviewer',prompt:'Investigate'}),/taakcontract/);assert.throws(()=>agent(r,'Explore'),/niet toegestaan/);});
test('A08: agent total survives route reassessment',t=>{const r=fixture(t);begin(r);const c=task({mode:'standard',agents:[specialist('aae-code-reviewer',2)],budget:{agent_calls:2,max_parallel:1,command_runs:0}});installTask(r,c);finish(r,agent(r));finish(r,agent(r));route(r);assert.throws(()=>agent(r),/agentbudget/);assert.equal(state(r).task.usage.agents,2);});
test('agent reservation is idempotent for same tool id',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));const input={subagent_type:'aae-code-reviewer',prompt:'Specific scope'};pre(r,'Agent',input,{tool_use_id:'call-1'});pre(r,'Agent',input,{tool_use_id:'call-1'});assert.equal(state(r).task.usage.agents,1);assert.throws(()=>pre(r,'Agent',{...input,prompt:'Different'},{tool_use_id:'call-1'}),/hergebruikt/);});
test('selected model is inserted instead of requested expensive override',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));const c=agent(r,'aae-code-reviewer',{model:'opus'});assert.equal(c.res.hookSpecificOutput.updatedInput.model,'sonnet');assert.match(c.res.hookSpecificOutput.updatedInput.prompt,/VERPLICHT AAE/);});
test('bootstrap supervisor is limited and counts in total budget',t=>{const r=fixture(t);begin(r);finish(r,agent(r,'aae-supervisor'),'aae-supervisor');assert.throws(()=>agent(r,'aae-supervisor'),/al een supervisor/);installTask(r,task({mode:'standard',agents:[specialist()],budget:{agent_calls:2,max_parallel:1,command_runs:0}}));assert.equal(state(r).task.usage.agents,1);finish(r,agent(r));assert.equal(state(r).task.usage.agents,2);});
test('route cannot be created while bootstrap is live',t=>{const r=fixture(t);begin(r);agent(r,'aae-supervisor');put(r,TASK,task({budget:{agent_calls:1,max_parallel:1,command_runs:0}}));assert.throws(()=>route(r),/loopt nog een agent/);});
test('no additional supervisor when route budget is zero',t=>{const r=fixture(t);begin(r);installTask(r,task());assert.throws(()=>agent(r,'aae-supervisor'),/budget/);});
test('new task id cannot reset budget in same request',t=>{const r=fixture(t);begin(r);installTask(r,task());put(r,TASK,task({id:'T-002'}));assert.throws(()=>route(r),/nieuw taak-ID/);});
test('A09/A10: known and unknown subagents cannot write or run shell',t=>{const r=fixture(t);begin(r);installTask(r,task());for(const role of ['general-purpose','aae-code-reviewer']){assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'evil'},{agent_id:'a',agent_type:role}),/read-only/);assert.throws(()=>pre(r,'Bash',{command:'npm run test'},{agent_id:'a',agent_type:role}),/read-only/);}});
test('agents cannot delegate to other agents',t=>{const r=fixture(t);begin(r);assert.throws(()=>pre(r,'Agent',{subagent_type:'aae-supervisor',prompt:'spawn'},{agent_id:'a',agent_type:'aae-code-reviewer'}),/geen andere agents/);});
test('unregistered agent reads blocked; registered packet reads allowed',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));assert.throws(()=>pre(r,'Read',{file_path:path.join(r,'src/a.js')},{agent_id:'unknown',agent_type:'aae-code-reviewer'}),/geregistreerde/);const a=agent(r);handleEvent(r,ev(r,'SubagentStart',{agent_id:'a',agent_type:'aae-code-reviewer'}));assert.doesNotThrow(()=>pre(r,'Read',{file_path:path.join(r,'src/a.js')},{agent_id:'a',agent_type:'aae-code-reviewer'}));assert.throws(()=>pre(r,'Grep',{pattern:'everything'},{agent_id:'a',agent_type:'aae-code-reviewer'}),/werkpakket/);});
test('concurrent reservations are refused at limit one',t=>{const r=fixture(t);begin(r);installTask(r,task({mode:'standard',agents:[specialist(),specialist('aae-test-writer')],budget:{agent_calls:2,max_parallel:1,command_runs:0}}));agent(r);assert.throws(()=>agent(r,'aae-test-writer'),/reserveert/);});
test('explicit approved parallel two supports distinct readonly roles',t=>{const r=fixture(t);begin(r);const result=installTask(r,task({mode:'standard',agents:[specialist(),specialist('aae-test-writer')],budget:{agent_calls:2,max_parallel:2,command_runs:0},parallel_reason:'Twee onafhankelijke readonly vragen met gescheiden context.'}));assert.equal(result.status,'pending');prompt(r,'AAE GO');agent(r);assert.doesNotThrow(()=>agent(r,'aae-test-writer'));});
test('background telemetry does not free a slot prematurely',t=>{const r=fixture(t);begin(r);installTask(r,task({mode:'standard',agents:[specialist('aae-code-reviewer',2)],budget:{agent_calls:2,max_parallel:1,command_runs:0}}));const a=agent(r);handleEvent(r,ev(r,'PostToolUse',{tool_name:'Agent',tool_use_id:a.toolId,tool_response:{status:'async_launched',agentId:'a'}}));assert.throws(()=>agent(r),/reserveert/);handleEvent(r,ev(r,'SubagentStop',{agent_id:'a',agent_type:'aae-code-reviewer',last_assistant_message:'STATUS: READY'}));assert.doesNotThrow(()=>agent(r));});
test('failed launch consumes budget but frees reservation',t=>{const r=fixture(t);begin(r);installTask(r,task({mode:'standard',agents:[specialist('aae-code-reviewer',2)],budget:{agent_calls:2,max_parallel:1,command_runs:0}}));const a=agent(r);handleEvent(r,ev(r,'PostToolUseFailure',{tool_name:'Agent',tool_use_id:a.toolId}));agent(r);assert.equal(state(r).task.usage.agents,2);});
test('source writes are refused during review',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));agent(r);assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'changed'}),/bronwijzigingen/);});
test('resume of stale source context is rejected',t=>{const r=fixture(t);begin(r);installTask(r,task({mode:'standard',agents:[specialist('aae-code-reviewer',2)],budget:{agent_calls:2,max_parallel:1,command_runs:0}}));const id=finish(r,agent(r));put(r,'src/a.js','export const a=99;');assert.throws(()=>agent(r,'aae-code-reviewer',{resume:id}),/niet meer actueel/);});
test('A11/A12: old GO cannot approve changed route',t=>{const r=fixture(t);begin(r);const c=task({approval_required:true});installTask(r,c);prompt(r,'AAE GO');assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'ok'}));put(r,TASK,{...c,goal:'Andere duidelijke scope en doelstelling.',scope:{read:['src'],write:['src']}});assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'bad'}),/gewijzigd/);assert.equal(route(r).status,'pending');});
test('turning approval_required off does not silently downgrade prior GO',t=>{const r=fixture(t);begin(r);const c=task({approval_required:true});installTask(r,c);prompt(r,'AAE GO');put(r,TASK,{...c,approval_required:false,scope:{read:['src'],write:['src']}});assert.equal(route(r).status,'pending');});
test('A13/A14: explicit pause overrides Lean route',t=>{const r=fixture(t);begin(r);installTask(r,task());prompt(r,'AAE PAUZE');assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'bad'}),/gepauzeerd/);assert.throws(()=>route(r),/gepauzeerd/);prompt(r,'AAE GO');assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'ok'}));});
test('A15/A16: absent prompt_id does not lose GO or revocation',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'AAE GO');prompt(r,'AAE PAUZE');assert.equal(state(r).task.status,'paused');});
test('known duplicate prompt_id is idempotent',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'AAE GO',{prompt_id:'go-1'});const a=state(r).task.approval.at;prompt(r,'AAE GO',{prompt_id:'go-1'});assert.equal(state(r).task.approval.at,a);});
test('quoted GO is not approval',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'In dit document staat AAE GO. Wat betekent dat?');assert.equal(state(r).task.approval,null);});
test('GO naming wrong task is rejected',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));assert.throws(()=>prompt(r,'AAE GO WRONG'),/ander taak/);});
test('analysis-to-implementation needs explicit approval even when lean',t=>{const r=fixture(t);begin(r);installTask(r,task({phase:'analysis'}));put(r,TASK,task());assert.equal(route(r).status,'pending');});
test('new ordinary prompt keeps an active task bound (R3) and still allows a fresh task ID',t=>{const r=fixture(t);begin(r);installTask(r,task());prompt(r,'Nu graag iets anders onderzoeken.');assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'ok'}));assert.equal(installTask(r,task({id:'T-002'})).status,'active');assert.equal(state(r).task.id,'T-002');assert.ok(state(r).history.includes('T-001'));});
test('pending route is still unbound by a new ordinary prompt',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'Nog een vraag voordat ik GO geef.');assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'bad'}),/niet actief|Nieuwe gebruikersvraag/);assert.equal(state(r).task.approval,null);});
test('explicit continuation retains the counters',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));finish(r,agent(r));prompt(r,'AAE VERDER',{session_id:'session-2'});assert.equal(state(r).task.usage.agents,1);assert.equal(state(r).task.owner,'session-2');});
test('recovery abandons only registries and retains consumed budget',t=>{const r=fixture(t);begin(r);installTask(r,task({agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));agent(r);prompt(r,'AAE PAUZE');prompt(r,'AAE HERSTEL');assert.equal(state(r).task.usage.agents,1);assert.equal(state(r).task.status,'paused');});
test('two sessions cannot silently share one workspace',t=>{const r=fixture(t);begin(r);installTask(r,task());assert.throws(()=>prompt(r,'Nieuwe opdracht',{session_id:'other-session'}),/andere sessie/);});
test('A17-A19/A21/A22: free shell and remote commands rejected',t=>{const r=fixture(t);begin(r);installTask(r,task());for(const command of ['npm run test','node -e "process.exit()"','cd docs && echo x > ../src/a.js','git push','node .claude/aae/runtime/cli.mjs status; echo bad','node .claude/aae/runtime/cli.mjs run t > file'])assert.throws(()=>pre(r,'Bash',{command}),/vrije shell/);assert.throws(()=>pre(r,'PowerShell',{command:'Set-Content src/a.js evil'}),/vrije shell/);});
test('controlled runner interface accepted without bypassing host permissions',t=>{const r=fixture(t);begin(r);assert.equal(pre(r,'Bash',{command:'node .claude/aae/runtime/cli.mjs status'}),null);assert.equal(pre(r,'PowerShell',{command:'node .claude/aae/runtime/cli.mjs doctor'}),null);});
test('A23/A24: old PROGRESS level does not change new route',t=>{const r=fixture(t);begin(r);put(r,'docs/PROGRESS.md','Kwaliteitsniveau: 1\n');installTask(r,task({approval_required:true}));assert.equal(state(r).task.status,'pending');});
test('new unknown tools and agentteams cannot bypass routing',t=>{const r=fixture(t);begin(r);for(const n of ['TeamCreate','mcp__github__push_files','Skill'])assert.throws(()=>pre(r,n,{}),/niet door AAE/);});
test('bypassPermissions mode is rejected',t=>{const r=fixture(t);begin(r);assert.throws(()=>pre(r,'Read',{file_path:path.join(r,'src/a.js')},{permission_mode:'bypassPermissions'}),/bypassPermissions/);});
test('hook entrypoint resolves project root and catches invalid JSON',t=>{const r=fixture(t);const script=path.join(r,'.claude/aae/runtime/hook.mjs');let out=spawnSync(process.execPath,[script],{input:JSON.stringify(ev(r,'SessionStart')),encoding:'utf8'});assert.equal(out.status,0,out.stderr);assert.match(out.stdout,/AAE v3\.2-local geladen/);out=spawnSync(process.execPath,[script],{input:'{bad',encoding:'utf8'});assert.equal(out.status,2);});
test('corrupt state fails closed rather than silently resetting',t=>{const r=fixture(t);begin(r);put(r,'.claude/aae/state/local.json','{bad');const out=spawnSync(process.execPath,[path.join(r,'.claude/aae/runtime/hook.mjs')],{input:JSON.stringify(ev(r,'PreToolUse',{tool_name:'Write',tool_input:{file_path:path.join(r,'src/a.js'),content:'bad'}})),encoding:'utf8'});assert.equal(out.status,2);});
test('source fingerprint changes when relevant untracked files change',t=>{const r=fixture(t);const c=task();const a=sourceDigest(r,c);put(r,'src/new.js','new file');assert.notEqual(sourceDigest(r,c),a);});
test('Stop hook does not force more work or a review loop',t=>{const r=fixture(t);begin(r);installTask(r,task());assert.equal(handleEvent(r,ev(r,'Stop',{stop_hook_active:true})),null);});

// --- v3.2-local: één GO per werkpakket ---
test('R3: follow-up prompt keeps the approved route and its GO',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'AAE GO');prompt(r,'Rooktest ok, ga verder.');assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'ok'}));const s=state(r);assert.equal(s.task.status,'active');assert.equal(s.task.approval.request_key,s.request.key);});
test('R3: explicit pause is not revived by a follow-up prompt',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'AAE GO');prompt(r,'AAE PAUZE');prompt(r,'Hoe staat het ervoor?');assert.throws(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'bad'}),/gepauzeerd/);assert.equal(state(r).task.approval,null);});
test('R3: follow-up prompt from another session does not take over',t=>{const r=fixture(t);begin(r);installTask(r,task({approval_required:true}));prompt(r,'AAE GO');assert.throws(()=>prompt(r,'Ik neem het over.',{session_id:'other-session'}),/andere sessie/);});
test('R4: amendment inside the approved envelope keeps the GO',t=>{const r=fixture(t);begin(r);const c=task({approval_required:true,scope:{read:['src'],write:['src']}});installTask(r,c);prompt(r,'AAE GO');const res=installTask(r,{...c,goal:'Zelfde doel, andere technische uitwerking binnen dezelfde scope.',scope:{read:['src','docs'],write:['src/a.js']},acceptance:[...c.acceptance,{id:'AC2',text:'Extra controle binnen dezelfde scope.'}]});assert.equal(res.status,'active');assert.equal(res.amended,true);assert.deepEqual(res.envelope_changes,[]);assert.doesNotThrow(()=>pre(r,'Write',{file_path:path.join(r,'src/a.js'),content:'ok'}));assert.equal(state(r).task.approval.digest,state(r).task.digest);});
test('R4: material changes leave the envelope and need a new GO',t=>{
  const base=task({approval_required:true,mode:'standard',scope:{read:['src'],write:['src/a.js']},agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:2,external_calls:0},commands:[{id:'t1',argv:['node','x.mjs'],purpose:'test',why:'Controleer de regel.',watch:[],timeout_ms:3000,max_runs:1}]});
  const variants=[
    ['schrijfscope',{scope:{read:['src'],write:['src']}}],
    ['commando',{commands:[...base.commands,{id:'p1',argv:['git','push'],purpose:'publish',why:'Publiceer de wijziging.',watch:[],timeout_ms:3000,max_runs:1}]}],
    ['risico',{risk:'normal'}],
    ['agent',{agents:[specialist(),specialist('aae-test-writer')],budget:{...base.budget,agent_calls:2}}],
    ['budget',{budget:{...base.budget,agent_calls:2}}],
    ['risicovlaggen',{risk_flags:['ui'],test_plan:[...base.test_plan,{kind:'visual',method:'manual',description:'Bekijk het scherm.'},{kind:'accessibility',method:'manual',description:'Controleer labels.'}]}],
    ['goedkeuringsvlaggen',{design_freeze:true}],
    ['fase',{phase:'analysis',scope:{read:['src'],write:[]},commands:[],test_plan:[{kind:'analysis',method:'inspection',description:'Onderbouw het antwoord met de relevante bron.'}]}]
  ];
  for(const [reason,patch] of variants){const r=fixture(t);begin(r);assert.equal(installTask(r,base).status,'pending');prompt(r,'AAE GO');const res=installTask(r,{...base,...patch});assert.equal(res.status,'pending',reason);assert.ok(res.envelope_changes.some(x=>x.startsWith(reason)),reason+': '+res.envelope_changes.join(','));assert.equal(state(r).task.approval,null,reason);}
});
test('R4/R7: new local test command stays inside the envelope, a removed decision point does not',t=>{const r=fixture(t);begin(r);const base=task({approval_required:true,decision_points:['Vraag Jurgen voor het verwijderen van gegevens.']});installTask(r,base);prompt(r,'AAE GO');const withTest={...base,budget:{...base.budget,command_runs:3},commands:[{id:'unit',argv:['node','--test','src'],purpose:'test',why:'Gerichte test binnen de scope.',watch:[],timeout_ms:3000,max_runs:3}]};const a=installTask(r,withTest);assert.equal(a.status,'active');assert.equal(a.amended,true);const b=installTask(r,{...withTest,decision_points:[]});assert.equal(b.status,'pending');assert.ok(b.envelope_changes.includes('beslisgrenzen'));});
test('R5/R7/R12: schema limits for runs, gates and decision points',()=>{
  const c=x=>task({budget:{agent_calls:0,max_parallel:1,command_runs:80},commands:[{id:'c',argv:['node','x.mjs'],purpose:'test',why:'Controleer de regel.',watch:[],timeout_ms:3000,max_runs:1,...x}]});
  assert.doesNotThrow(()=>validateTask(c({max_runs:20})));
  assert.throws(()=>validateTask(c({max_runs:21})),/Aantal uitvoeringen/);
  assert.doesNotThrow(()=>validateTask(c({purpose:'publish',max_runs:10})));
  assert.throws(()=>validateTask(c({purpose:'publish',max_runs:11})),/Aantal uitvoeringen/);
  assert.throws(()=>validateTask(c({purpose:'install',max_runs:2})),/Aantal uitvoeringen|Installeren/);
  assert.throws(()=>validateTask(c({purpose:'destructive',max_runs:2})),/Aantal uitvoeringen|destructief/);
  assert.doesNotThrow(()=>validateTask(c({purpose:'publish',gate:'ready'})));
  assert.throws(()=>validateTask(c({gate:'soms'})),/gate/);
  assert.doesNotThrow(()=>validateTask(task({decision_points:['Vraag Jurgen voor een merge naar main.']})));
  assert.throws(()=>validateTask(task({decision_points:Array.from({length:9},(_,i)=>'Beslisgrens nummer '+i)})),/Beslisgrenzen/);
  assert.throws(()=>validateTask(task({budget:{agent_calls:0,max_parallel:1,command_runs:81}})),/Commandobudget/);
});
test('B1: a command cannot change its purpose or sneak publishing argv in as a local test',t=>{
  const base=task({approval_required:true,mode:'standard',budget:{agent_calls:0,max_parallel:1,command_runs:4},commands:[{id:'push',argv:['git','push','origin','claude/x'],purpose:'publish',why:'Push naar de werkbranch.',watch:[],timeout_ms:3000,max_runs:1}]});
  const variants=[
    ['commando-doel',{commands:[{...base.commands[0],purpose:'test'}]}],
    ['commando',{commands:[...base.commands,{id:'sneaky',argv:['git','push','origin','claude/x:main'],purpose:'test',why:'Zogenaamd een test.',watch:[],timeout_ms:3000,max_runs:1}]}],
    ['commando',{commands:[...base.commands,{id:'fixer',argv:['npx','eslint','--fix','src'],purpose:'test',why:'Lint met automatische fix.',watch:[],timeout_ms:3000,max_runs:1}]}],
    ['commando',{commands:[...base.commands,{id:'script',argv:['node','scripts/onbekend.mjs'],purpose:'test',why:'Onbekend eigen script.',watch:[],timeout_ms:3000,max_runs:1}]}]
  ];
  for(const [reason,patch] of variants){const r=fixture(t);begin(r);installTask(r,base);prompt(r,'AAE GO');const res=installTask(r,{...base,...patch});assert.equal(res.status,'pending',reason);assert.ok(res.envelope_changes.some(x=>x.startsWith(reason)),reason+': '+res.envelope_changes.join(','));}
  const r=fixture(t);begin(r);installTask(r,base);prompt(r,'AAE GO');assert.equal(installTask(r,{...base,commands:[...base.commands,{id:'vt',argv:['npx','vitest','run','src'],purpose:'test',why:'Gerichte test.',watch:[],timeout_ms:3000,max_runs:3}]}).status,'active');
});
test('B2: evidence and READY requirements cannot be weakened inside the envelope',t=>{
  const base=task({approval_required:true,mode:'standard',risk_flags:['external_effects'],agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0},acceptance:[{id:'AC1',text:'De hoofdregel werkt.'},{id:'AC2',text:'Foutafhandeling is getest.'}],test_plan:[{kind:'scope',method:'inspection',description:'Scope gecontroleerd.'},{kind:'functional',method:'command',description:'Gerichte test.'},{kind:'regression',method:'command',description:'Snelle suite.'},{kind:'failure-handling',method:'inspection',description:'Fout zonder retrylus.'},{kind:'accessibility',method:'manual',description:'Extra handmatige controle van labels.'}]});
  const variants=[
    ['acceptatiecriteria',{acceptance:[base.acceptance[0]]}],
    ['acceptatiecriteria',{acceptance:[base.acceptance[0],{id:'AC2',text:'Iets lichters.'}]}],
    ['risicovlaggen',{risk_flags:[]}],
    ['bewijsplan',{test_plan:base.test_plan.map(x=>x.kind==='functional'?{...x,method:'inspection'}:x)}],
    ['bewijsplan',{test_plan:base.test_plan.filter(x=>x.kind!=='accessibility')}],
    ['modus',{mode:'lean',agents:[specialist()]}],
    ['agent verwijderd',{agents:[],budget:{...base.budget,agent_calls:0}}],
    ['agent',{agents:[{...specialist(),question:'Een lichtere vraag zonder regressiecontrole?'}]}],
    ['agent',{agents:[{...specialist(),files:[]}]}],
    ['bewijsplan',{test_plan:base.test_plan.map(x=>x.kind==='regression'?{...x,description:'Alleen even kijken.'}:x)}],
    ['goedkeuringsvlaggen',{approval_required:false}]
  ];
  for(const [reason,patch] of variants){const r=fixture(t);begin(r);installTask(r,base);prompt(r,'AAE GO');let res;try{res=installTask(r,{...base,...patch});}catch(e){assert.fail(reason+': contract ongeldig: '+e.message);}assert.equal(res.status,'pending',reason);assert.ok(res.envelope_changes.some(x=>x.startsWith(reason)),reason+': '+res.envelope_changes.join(','));}
});
test('B5: a READY gate on a command cannot silently disappear inside the envelope',t=>{const r=fixture(t);begin(r);const base=task({approval_required:true,budget:{agent_calls:0,max_parallel:1,command_runs:2},commands:[{id:'unit',argv:['node','--test','src'],purpose:'test',why:'Gerichte test met gate.',watch:[],timeout_ms:3000,max_runs:2,gate:'ready'}]});installTask(r,base);prompt(r,'AAE GO');const res=installTask(r,{...base,commands:[{...base.commands[0],gate:'none'}]});assert.equal(res.status,'pending');assert.ok(res.envelope_changes.includes('commando-gate unit'),res.envelope_changes.join(','));const r2=fixture(t);begin(r2);installTask(r2,base);prompt(r2,'AAE GO');const {gate,...withoutGate}=base.commands[0];assert.equal(installTask(r2,{...base,commands:[withoutGate]}).status,'pending');});
test('B1/B3: safe local argv is an allowlist of programs, flags and plain relative operands',async()=>{const {safeLocalArgv}=await import('../runtime/core.mjs');
  for(const ok of [['node','--test','tests/a.test.mjs'],['node','--test','tests'],['node','--test','.claude/aae/tests/guard.test.mjs'],['npx','vitest','run'],['npx','vitest','run','src/x.test.ts'],['npx','tsc','--noEmit'],['npx','eslint','--max-warnings=0','src'],['git','status','--porcelain'],['git','log','--oneline','-n5'],['git','diff','--stat','origin/main...HEAD'],['git','merge-base','--is-ancestor','origin/main','HEAD']])assert.equal(safeLocalArgv(ok),true,ok.join(' '));
  for(const bad of [['git','diff','--output=x'],['npx','vitest','-u'],['npx','vitest','run','--outputFile=x'],['npx','vitest'],['npm','run','test'],['git','push'],['git','push','origin','x:main'],['node','--test','--import','./evil.mjs'],['node','--test','../buiten.test.mjs'],['node','--test','/abs/x.test.mjs'],['npx','eslint','--fix','src'],['npx','tsc','--noEmit','--outDir','x'],['git','log','-n99999'],['node','scripts/x.mjs'],['node','--test','scripts/x.mjs'],['node','--test','scripts/evil'],['node','--test','src/payload.mjs'],'git status'])assert.equal(safeLocalArgv(bad),false,String(bad));
});
test('all shipped example contracts validate',async()=>{const {payload}=await import('./helpers.mjs');const dir=path.join(payload,'.claude/aae/examples');const files=fs.readdirSync(dir).filter(f=>f.endsWith('.json'));assert.ok(files.includes('06-werkpakket-met-merge.json'));for(const f of files)assert.doesNotThrow(()=>validateTask(JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'))),f);});
