import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fixture,begin,prompt,pre,task,specialist,installTask,ev,state} from './helpers.mjs';
import {handleEvent} from '../runtime/events.mjs';
import {classifyExternalCall} from '../runtime/integrations.mjs';

const REF='takenlijst-ref';
function post(root,id,name,response={content:[{type:'text',text:'ok'}]}){return handleEvent(root,ev(root,'PostToolUse',{tool_name:name,tool_use_id:id,tool_response:response}));}
function fail(root,id,name){return handleEvent(root,ev(root,'PostToolUseFailure',{tool_name:name,tool_use_id:id,tool_response:{error:'nope'}}));}
function call(root,name,input={}){const id='ext-'+Math.random().toString(36).slice(2);const res=handleEvent(root,ev(root,'PreToolUse',{tool_name:name,tool_input:input,tool_use_id:id}));return {id,res};}
function verify(root){const c=call(root,'mcp__supabase__get_project_url');post(root,c.id,'mcp__supabase__get_project_url',{content:[{type:'text',text:`Project API URL: https://${REF}.supabase.co`} ]});assert.equal(state(root).integrations.supabase.verified_ref,REF);}
function integrationTask(overrides={}){
  const base=task({phase:'analysis',mode:'standard',risk:'normal',uncertainty:'low',risk_flags:[],scope:{read:['src'],write:[]},integrations:{supabase:{project_ref:REF,tools:['get_project_url','list_migrations','execute_sql'],max_calls:6}},budget:{agent_calls:0,max_parallel:1,command_runs:0,external_calls:6}});
  return {...base,...overrides};
}
function migrationTask(overrides={}){
  const c=integrationTask({phase:'implementation',risk_flags:['migration'],integrations:{supabase:{project_ref:REF,tools:['get_project_url','list_migrations','apply_migration'],max_calls:6}},test_plan:[
    {kind:'scope',method:'inspection',description:'Controleer projectbinding en afgesproken scope.'},
    {kind:'functional',method:'inspection',description:'Controleer het bedoelde databasegedrag.'},
    {kind:'regression',method:'inspection',description:'Controleer relevante regressierisicos.'},
    {kind:'migration',method:'inspection',description:'Controleer migratie-uitvoering.'},
    {kind:'rollback',method:'inspection',description:'Controleer herstelpad of idempotentie.'},
    {kind:'data-preservation',method:'inspection',description:'Controleer gegevensbehoud.'}
  ]});return {...c,...overrides};
}

test('I01: get_project_url is the only bounded pre-route Supabase probe',t=>{const r=fixture(t);begin(r);verify(r);assert.throws(()=>call(r,'mcp__supabase__list_migrations'),/route/);});
test('I02: known read-only Supabase tool allowed in active route',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());const c=call(r,'mcp__supabase__list_migrations');assert.equal(c.res,null);post(r,c.id,'mcp__supabase__list_migrations',{migrations:[]});assert.equal(state(r).task.usage.external,1);});
test('I03: unknown Supabase tool stays blocked',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());assert.throws(()=>call(r,'mcp__supabase__drop_database'),/niet door AAE/);});
test('I04: SELECT via execute_sql is allowed and receipt stores no raw result',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());const c=call(r,'mcp__supabase__execute_sql',{query:'select count(*) from public.tasks'});post(r,c.id,'mcp__supabase__execute_sql',{content:[{type:'text',text:'SECRET_VALUE user@example.com'}]});const st=state(r),p=st.task.external_receipts[0].evidence_path,txt=fs.readFileSync(path.join(r,p),'utf8');assert.doesNotMatch(txt,/SECRET_VALUE|user@example/);assert.match(txt,/result_digest/);});
test('I05: UPDATE via execute_sql cannot run as ordinary read/change',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());assert.throws(()=>call(r,'mcp__supabase__execute_sql',{query:"update public.tasks set status='done'"}),/AAE GO/);});
test('I06: apply_migration is blocked before AAE GO and allowed after GO',t=>{const r=fixture(t);begin(r);verify(r);const route=installTask(r,migrationTask());assert.equal(route.status,'pending');assert.throws(()=>call(r,'mcp__supabase__apply_migration',{name:'add_index',query:'create index if not exists x on public.tasks(id)'}),/AAE GO/);prompt(r,'AAE GO');const c=call(r,'mcp__supabase__apply_migration',{name:'add_index',query:'create index if not exists x on public.tasks(id)'});post(r,c.id,'mcp__supabase__apply_migration',{ok:true});assert.equal(state(r).task.external_receipts[0].status,'stopped');});
test('I07: external provider budget is independent from agent budget',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());const c=call(r,'mcp__supabase__list_migrations');post(r,c.id,'mcp__supabase__list_migrations',{migrations:[]});assert.equal(state(r).task.usage.external,1);assert.equal(state(r).task.usage.agents,0);});
test('I08: wrong Supabase project input is blocked',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());assert.throws(()=>call(r,'mcp__supabase__list_migrations',{project_ref:'other-project'}),/ander project/);});
test('I09: failed Supabase call consumes budget but does not spawn repair agents',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());const c=call(r,'mcp__supabase__list_migrations');fail(r,c.id,'mcp__supabase__list_migrations');const st=state(r);assert.equal(st.task.usage.external,1);assert.equal(st.task.usage.agents,0);assert.equal(st.task.external_calls[c.id].status,'failed');});
test('I10: sensitive SQL needs exact plan plus separate sensitive GO',t=>{const r=fixture(t);begin(r);verify(r);const sql='drop table public.temporary_old';const c=task({mode:'high-assurance',risk:'high',uncertainty:'low',risk_flags:[],scope:{read:['src'],write:[]},agents:[specialist('aae-code-reviewer')],integrations:{supabase:{project_ref:REF,tools:['get_project_url','execute_sql'],max_calls:3,dangerous_sql:[sql]}},budget:{agent_calls:1,max_parallel:1,command_runs:0,external_calls:3}});installTask(r,c);prompt(r,'AAE GO');assert.throws(()=>call(r,'mcp__supabase__execute_sql',{query:sql}),/GEVOELIG GO/);prompt(r,'AAE GEVOELIG GO T-001');assert.doesNotThrow(()=>call(r,'mcp__supabase__execute_sql',{query:sql}));});
test('I11: ToolSearch is allowed for main session but not subagents',t=>{const r=fixture(t);begin(r);assert.equal(pre(r,'ToolSearch',{query:'supabase'}),null);assert.throws(()=>pre(r,'ToolSearch',{query:'supabase'},{agent_id:'a',agent_type:'aae-code-reviewer'}),/read-only/);});
test('I12: GitHub PR creation is route-bound and merge remains unknown/blocked',t=>{const r=fixture(t);begin(r);const c=task({mode:'standard',risk_flags:['external_effects'],scope:{read:['src'],write:[]},test_plan:[{kind:'scope',method:'inspection',description:'Controleer PR-scope.'},{kind:'functional',method:'inspection',description:'Controleer PR-aanmaak.'},{kind:'regression',method:'inspection',description:'Controleer dat geen merge plaatsvindt.'},{kind:'failure-handling',method:'inspection',description:'Controleer foutafhandeling zonder retrylus.'}],integrations:{github:{tools:['create_pull_request'],max_calls:1,base:'main',head:'claude/feature'}},budget:{agent_calls:0,max_parallel:1,command_runs:0,external_calls:1}});assert.equal(installTask(r,c).status,'pending');assert.throws(()=>call(r,'mcp__GitHub__create_pull_request',{base:'main',head:'claude/feature',title:'Feature'}),/AAE GO/);prompt(r,'AAE GO');assert.doesNotThrow(()=>call(r,'mcp__GitHub__create_pull_request',{base:'main',head:'claude/feature',title:'Feature'}));assert.throws(()=>call(r,'mcp__GitHub__merge_pull_request',{pull_number:1}),/niet door AAE/);});
test('I13: migration flag no longer forces High Assurance by itself',()=>{assert.doesNotThrow(()=>migrationTask());});

test('I14: SQL classifier rejects side-effect SELECT and multiple statements',()=>{assert.equal(classifyExternalCall('mcp__supabase__execute_sql',{query:"select set_config('x','y',false)"}).level,'sensitive');assert.equal(classifyExternalCall('mcp__supabase__execute_sql',{query:'select 1; select 2'}).level,'sensitive');});
test('I15: function-body DML in apply_migration is not mistaken for immediate DELETE',()=>{const sql=`create or replace function public.cleanup() returns void language plpgsql as $$ begin delete from public.old_rows where false; end; $$;`;assert.equal(classifyExternalCall('mcp__supabase__apply_migration',{name:'cleanup_fn',query:sql}).level,'change');});

test('I16: new ordinary prompt may re-probe Supabase without reviving old route',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());prompt(r,'Nieuwe databasevraag.');const c=call(r,'mcp__supabase__get_project_url');assert.equal(c.res,null);});

test('I17: Supabase verification is scoped to the current user request',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,integrationTask());prompt(r,'Nieuwe databasevraag.');installTask(r,integrationTask());assert.throws(()=>call(r,'mcp__supabase__list_migrations'),/deze gebruikersvraag live geverifieerd/);verify(r);assert.doesNotThrow(()=>call(r,'mcp__supabase__list_migrations'));});
test('I18: apply_migration fails closed without explicit name or SQL',t=>{const r=fixture(t);begin(r);verify(r);installTask(r,migrationTask());prompt(r,'AAE GO');assert.throws(()=>call(r,'mcp__supabase__apply_migration',{name:'',query:'create table public.x(id int)'}),/migratienaam/);assert.throws(()=>call(r,'mcp__supabase__apply_migration',{name:'x',query:''}),/migratie-SQL/);});
test('I19: GitHub PR creation requires explicit matching base and head',t=>{const r=fixture(t);begin(r);const c=task({mode:'standard',risk_flags:['external_effects'],scope:{read:['src'],write:[]},test_plan:[{kind:'scope',method:'inspection',description:'Controleer PR-scope.'},{kind:'functional',method:'inspection',description:'Controleer PR-aanmaak.'},{kind:'regression',method:'inspection',description:'Controleer dat geen merge plaatsvindt.'},{kind:'failure-handling',method:'inspection',description:'Controleer foutafhandeling zonder retrylus.'}],integrations:{github:{tools:['create_pull_request'],max_calls:1,base:'main',head:'claude/feature'}},budget:{agent_calls:0,max_parallel:1,command_runs:0,external_calls:1}});installTask(r,c);prompt(r,'AAE GO');assert.throws(()=>call(r,'mcp__GitHub__create_pull_request',{title:'Feature'}),/expliciete base/);});
