import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import path from 'node:path';
import {fixture,task,specialist,begin,installTask,agent,ev,finish,state,pre,put} from './helpers.mjs';import {handleEvent} from '../runtime/events.mjs';
function setup(t,max=2){const root=fixture(t);begin(root);installTask(root,task({mode:'standard',agents:[specialist('aae-code-reviewer',max)],budget:{agent_calls:max,max_parallel:1,command_runs:0}}));return root;}
test('late async launch receipt does not resurrect finished slot',t=>{const root=setup(t);const a=agent(root);handleEvent(root,ev(root,'SubagentStart',{agent_id:'A',agent_type:'aae-code-reviewer'}));handleEvent(root,ev(root,'SubagentStop',{agent_id:'A',agent_type:'aae-code-reviewer',last_assistant_message:'STATUS: READY'}));handleEvent(root,ev(root,'PostToolUse',{tool_name:'Agent',tool_use_id:a.toolId,tool_response:{status:'async_launched',agentId:'A'}}));assert.equal(state(root).task.calls[a.toolId].status,'stopped');assert.doesNotThrow(()=>agent(root));});
test('resume lifecycle binds newest reservation, not old finished call',t=>{const root=setup(t);const a=agent(root);const id=finish(root,a);const b=agent(root,'aae-code-reviewer',{resume:id});handleEvent(root,ev(root,'SubagentStart',{agent_id:id,agent_type:'aae-code-reviewer'}));const s=state(root);assert.equal(s.task.calls[a.toolId].status,'stopped');assert.equal(s.task.calls[b.toolId].status,'running');handleEvent(root,ev(root,'SubagentStop',{agent_id:id,agent_type:'aae-code-reviewer',last_assistant_message:'STATUS: PARTIAL'}));assert.equal(state(root).task.calls[b.toolId].reported_status,'PARTIAL');});
test('handback report retained when stop message is empty',t=>{const root=setup(t);const a=agent(root);handleEvent(root,ev(root,'SubagentStart',{agent_id:'A',agent_type:'aae-code-reviewer'}));handleEvent(root,ev(root,'PostToolUse',{tool_name:'SubagentHandback',agent_id:'A',agent_type:'aae-code-reviewer',tool_input:{message:'Onderbouwd in src/a.js. STATUS: PARTIAL'}}));handleEvent(root,ev(root,'SubagentStop',{agent_id:'A',agent_type:'aae-code-reviewer'}));assert.equal(state(root).task.calls[a.toolId].reported_status,'PARTIAL');});
test('unregistered agent lifecycle does not gain read privileges',t=>{const root=setup(t);handleEvent(root,ev(root,'SubagentStart',{agent_id:'U',agent_type:'aae-code-reviewer'}));assert.throws(()=>pre(root,'Read',{file_path:path.join(root,'src/a.js')},{agent_id:'U',agent_type:'aae-code-reviewer'}),/Geen geldige/);});
test('actual separate hook processes cannot reserve two slots under max_parallel one',async t=>{const root=setup(t);const hook=path.join(root,'.claude/aae/runtime/hook.mjs');const call=id=>new Promise(resolve=>{const child=spawn(process.execPath,[hook],{cwd:root,stdio:['pipe','pipe','pipe']});let output='';child.stderr.on('data',x=>output+=x);child.on('close',code=>resolve({code,output}));child.stdin.end(JSON.stringify(ev(root,'PreToolUse',{tool_name:'Agent',tool_use_id:id,tool_input:{subagent_type:'aae-code-reviewer',prompt:'Controleer de concrete regressievraag.',run_in_background:false}})));});const results=await Promise.all([call('concurrent-A'),call('concurrent-B')]);assert.deepEqual(results.map(x=>x.code).sort(),[0,2]);assert.equal(state(root).task.usage.agents,1);});
test('auth session fixture never enters model Read output',t=>{const root=fixture(t);begin(root);put(root,'.claude/aae/private/cookies.json','{}');assert.throws(()=>pre(root,'Read',{file_path:path.join(root,'.claude/aae/private/cookies.json')}),/testauthcookies/);});
test('Agent last-request usage is not mislabeled whole-run usage',t=>{const root=setup(t);const a=agent(root);handleEvent(root,ev(root,'PostToolUse',{tool_name:'Agent',tool_use_id:a.toolId,tool_response:{status:'completed',resolvedModel:'real-observed',totalTokens:100,usage:{input_tokens:80,output_tokens:20}}}));const c=state(root).task.calls[a.toolId];assert.equal(c.observed_model,'real-observed');assert.equal(c.last_request_usage.input_tokens,80);assert.equal(c.total_tokens,undefined);});
