import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fixture,task,put,begin,prompt,installTask,specialist,agent,finish,state} from './helpers.mjs';
import {runCommand,reportTemplate,closeTask} from '../runtime/runner.mjs';
import {RESULT,sourceDigest,commandFingerprint} from '../runtime/core.mjs';
function cmd(overrides={}) {return {id:'test',argv:[process.execPath,'check.mjs'],purpose:'test',why:'Controleer de relevante logica.',watch:['check.mjs'],timeout_ms:3000,max_runs:1,...overrides};}
function setup(t,{c=cmd(),body='console.log("test geslaagd");',extra={}}={}) {const root=fixture(t);put(root,'check.mjs',body);begin(root);const config=task({commands:[c],budget:{agent_calls:0,max_parallel:1,command_runs:c.max_runs},...extra});installTask(root,config);return {root,config};}
function evidence(root,method='inspection',file='docs/aae/notes/proof.md') {put(root,file,'Gerichte handmatige controle; geen claim van een browsertest.');const report=reportTemplate(root);report.status='READY';report.summary='Hoofdregel en afbakening zijn gecontroleerd.';for(const x of [...report.criteria,...report.checks])Object.assign(x,{status:'passed',evidence:[file],note:'Onderbouwd met deze gerichte controle.'});return report;}
test('new project command waits for explicit user GO', async t=>{const {root}=setup(t);await assert.rejects(runCommand(root,'test'),/niet actief/);prompt(root,'AAE GO');assert.equal((await runCommand(root,'test')).exit_code,0);});
test('receipt includes actual exit, source digests, bounded output and runtime',async t=>{const {root}=setup(t);prompt(root,'AAE GO');const r=await runCommand(root,'test');assert.equal(r.exit_code,0);assert.equal(r.source_before,r.source_after);assert.match(r.tail,/geslaagd/);assert.ok(r.duration_ms>=0);assert.ok(fs.existsSync(path.join(root,r.evidence_path)));assert.equal(state(root).task.command_running,null);});
test('command run limit persists',async t=>{const {root}=setup(t);prompt(root,'AAE GO');await runCommand(root,'test');await assert.rejects(runCommand(root,'test'),/budget bereikt|Maximum/);});
test('script/config changes invalidate command approval',async t=>{const {root}=setup(t);prompt(root,'AAE GO');put(root,'check.mjs','console.log("changed");');await assert.rejects(runCommand(root,'test'),/niet goedgekeurd/);prompt(root,'AAE GO');assert.equal((await runCommand(root,'test')).exit_code,0);});
test('package manifest included in fingerprint even when not in watch',async t=>{const {root}=setup(t);prompt(root,'AAE GO');put(root,'package.json',{name:'changed'});await assert.rejects(runCommand(root,'test'),/niet goedgekeurd/);});
test('shell metacharacters are literal argv, never evaluated',async t=>{const c=cmd({argv:[process.execPath,'check.mjs','; touch pwned','$(touch pwned)']});const {root}=setup(t,{c,body:'console.log(process.argv.slice(2).join("|"));'});prompt(root,'AAE GO');const r=await runCommand(root,'test');assert.match(r.tail,/touch pwned/);assert.equal(fs.existsSync(path.join(root,'pwned')),false);});
test('timeout produces a recorded failed receipt',async t=>{const {root}=setup(t,{c:cmd({timeout_ms:1000}),body:'setInterval(()=>{},10000);'});prompt(root,'AAE GO');const r=await runCommand(root,'test');assert.equal(r.timed_out,true);assert.notEqual(r.exit_code,0);assert.equal(state(root).task.command_running,null);});
test('missing executable produces bounded error without a busy registry',async t=>{const {root}=setup(t,{c:cmd({argv:['definitely-missing-aae-executable']})});prompt(root,'AAE GO');const r=await runCommand(root,'test');assert.notEqual(r.exit_code,0);assert.match(r.error,/ENOENT/);assert.equal(state(root).task.command_running,null);});
test('large command output is capped locally and in response',async t=>{const {root}=setup(t,{body:'process.stdout.write("x".repeat(1200000));'});prompt(root,'AAE GO');const r=await runCommand(root,'test');assert.ok(r.tail.length<=2500);assert.ok(fs.statSync(path.join(root,r.log_path)).size<=1024*1024);});
test('two identical failed runs require a changed hypothesis/source',async t=>{const {root}=setup(t,{c:cmd({max_runs:4}),body:'process.exit(1);'});prompt(root,'AAE GO');await runCommand(root,'test');await runCommand(root,'test');await assert.rejects(runCommand(root,'test'),/Twee gelijke/);put(root,'src/a.js','export const a=3;');assert.equal((await runCommand(root,'test')).exit_code,1);});
test('concurrent runner invocation is blocked',async t=>{const {root}=setup(t,{c:cmd({max_runs:2}),body:'setTimeout(()=>console.log("done"),150);'});prompt(root,'AAE GO');const p=runCommand(root,'test');await assert.rejects(runCommand(root,'test'),/Geen commandoloop/);await p;});
test('runner refuses a changed TASK.json without reroute',async t=>{const {root,config}=setup(t);prompt(root,'AAE GO');put(root,'docs/aae/TASK.json',{...config,title:'Een andere taak'});await assert.rejects(runCommand(root,'test'),/Taakcontract gewijzigd/);});
test('trust only selected local command types',async t=>{const {root,config}=setup(t);prompt(root,'AAE GO');prompt(root,'AAE VERTROUW');const r=await runCommand(root,'test');assert.equal(r.exit_code,0);prompt(root,'nieuwe concrete testopdracht');const next={...config,id:'T-002'};assert.equal(installTask(root,next).status,'active');assert.equal((await runCommand(root,'test')).exit_code,0);});
test('publish remains explicit, single-use and is not trusted',async t=>{const c=cmd({purpose:'publish'});const {root}=setup(t,{c});prompt(root,'AAE GO');prompt(root,'AAE VERTROUW');assert.equal(state(root).trusted_commands[commandFingerprint(root,c)],undefined);await runCommand(root,'test');await assert.rejects(runCommand(root,'test'));});
test('paused workflow cannot execute a previously approved command',async t=>{const {root}=setup(t);prompt(root,'AAE GO');prompt(root,'AAE PAUZE');await assert.rejects(runCommand(root,'test'),/gepauzeerd/);});
test('command cannot run while a reviewer is active',async t=>{const extra={agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:1}};const {root}=setup(t,{extra});prompt(root,'AAE GO');agent(root);await assert.rejects(runCommand(root,'test'),/Geen commandoloop/);});
test('default report is PARTIAL and does not claim unrun tests',t=>{const root=fixture(t);begin(root);installTask(root,task());const r=reportTemplate(root);assert.equal(r.status,'PARTIAL');assert.ok(r.checks.every(x=>x.status==='not_run'));});
test('READY cannot omit a required criterion or check',t=>{const root=fixture(t);begin(root);installTask(root,task());const r=evidence(root);r.checks=[];put(root,RESULT,r);assert.throws(()=>closeTask(root),/Verplichte controle/);});
test('READY refuses nonexistent evidence',t=>{const root=fixture(t);begin(root);installTask(root,task());const r=evidence(root);r.criteria[0].evidence=['missing.txt'];put(root,RESULT,r);assert.throws(()=>closeTask(root),/ENOENT/);});
test('READY rejects old-source evidence',t=>{const root=fixture(t);begin(root);installTask(root,task());const r=evidence(root);put(root,RESULT,r);put(root,'src/a.js','changed');assert.throws(()=>closeTask(root),/Broncode veranderd/);});
test('command proof must be an actual successful current receipt',async t=>{const checks=task().test_plan.map(x=>({...x,method:x.kind==='functional'?'command':'inspection'}));const {root}=setup(t,{extra:{test_plan:checks}});prompt(root,'AAE GO');const r=evidence(root);put(root,RESULT,r);assert.throws(()=>closeTask(root),/Geen succesvolle actuele/);const receipt=await runCommand(root,'test');r.checks.find(x=>x.kind==='functional').evidence=[receipt.evidence_path];put(root,RESULT,r);assert.equal(closeTask(root).status,'READY');});
test('a script that changes source cannot serve as unchanged-source test proof',async t=>{const checks=task().test_plan.map(x=>({...x,method:x.kind==='functional'?'command':'inspection'}));const {root}=setup(t,{extra:{test_plan:checks},body:'import fs from "node:fs";fs.writeFileSync("src/a.js","changed");'});prompt(root,'AAE GO');const rc=await runCommand(root,'test');const r=evidence(root);r.checks.find(x=>x.kind==='functional').evidence=[rc.evidence_path];put(root,RESULT,r);assert.throws(()=>closeTask(root),/Geen succesvolle actuele/);});
test('explicit additional planned check must also be completed',t=>{const root=fixture(t);begin(root);installTask(root,task({test_plan:[...task().test_plan,{kind:'visual',method:'manual',description:'Controleer het scherm.'}]}));const r=evidence(root);r.checks=r.checks.filter(x=>x.kind!=='visual');put(root,RESULT,r);assert.throws(()=>closeTask(root),/visual/);});
test('honest PARTIAL completion does not pretend deployment or readiness',t=>{const root=fixture(t);begin(root);installTask(root,task());put(root,RESULT,reportTemplate(root));const result=closeTask(root);assert.equal(result.status,'PARTIAL');assert.equal(result.not_deployed,true);assert.equal(state(root).task.status,'closed');});
test('high assurance needs actual independent current READY report',t=>{const root=fixture(t);begin(root);const c=task({mode:'high-assurance',risk:'high',agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}});installTask(root,c);prompt(root,'AAE GO');const r=evidence(root);put(root,RESULT,r);assert.throws(()=>closeTask(root),/onafhankelijk/);const a=agent(root);finish(root,a);assert.equal(closeTask(root).status,'READY');});
test('PARTIAL reviewer report is not independent READY evidence',t=>{const root=fixture(t);begin(root);installTask(root,task({mode:'high-assurance',risk:'high',agents:[specialist()],budget:{agent_calls:1,max_parallel:1,command_runs:0}}));prompt(root,'AAE GO');const a=agent(root);finish(root,a,'aae-code-reviewer','Niet getest. STATUS: PARTIAL');put(root,RESULT,evidence(root));assert.throws(()=>closeTask(root),/onafhankelijk/);});
